# Generated by Django 3.1.6 on 2021-03-17 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210316_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
