# Generated by Django 3.1.6 on 2021-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
